# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: hourly CI

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install libraries
        run: npm install
      - name: run hourly
        run: npm run hourly
      - name: Commit and push if changed
        run: |
          git add .
          git diff
          git config --global user.email "bengsiswantoh@gmail.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated Data" -a || echo "No changes to commit"
          git push
